## 1. 역명 통일시키기

* 2호선부터 시작하고 2호선이 태블루에서 전체(1~8호선)도 이름변경해서 수정하기!

In [1]:
import pandas as pd
import numpy as np

In [2]:
#2호선 parquet 불러오기
df = pd.read_parquet("second_line_per_time.parquet")
df

,호선,역명,요일,구분,06:00 이전,06:00 ~ 07:00,07:00 ~ 08:00,08:00 ~ 09:00,09:00 ~ 10:00,10:00 ~ 11:00,...,14:00 ~ 15:00,15:00 ~ 16:00,16:00 ~ 17:00,17:00 ~ 18:00,18:00 ~ 19:00,19:00 ~ 20:00,20:00 ~ 21:00,21:00 ~ 22:00,22:00 ~ 23:00,23:00 이후
0,2호선,강남,Monday,승차,224.0,591.0,1455.0,2408.0,1806.0,1633.0,...,3520.0,4520.0,4977.0,8257.0,13935.0,8619.0,5978.0,6759.0,5325.0,1305.0
1,2호선,강남,Monday,하차,467.0,2068.0,6424.0,13785.0,13135.0,5408.0,...,3425.0,3251.0,3136.0,3892.0,5753.0,3498.0,1529.0,1171.0,878.0,499.0
2,2호선,강남,Tuesday,승차,259.0,624.0,1510.0,2409.0,1797.0,1636.0,...,3585.0,4592.0,5131.0,8443.0,13780.0,8462.0,6200.0,7238.0,5815.0,1496.0
3,2호선,강남,Tuesday,하차,472.0,2012.0,6365.0,13685.0,13043.0,5436.0,...,3486.0,3308.0,3227.0,4098.0,6205.0,3818.0,1593.0,1247.0,1007.0,572.0
4,2호선,강남,Wednesday,승차,272.0,624.0,1498.0,2392.0,1782.0,1616.0,...,3559.0,4534.0,5051.0,8551.0,13617.0,8221.0,5958.0,7304.0,6089.0,1660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,2호선,홍대입구,Thursday,하차,120.0,515.0,1233.0,3881.0,3962.0,2316.0,...,2785.0,2850.0,3095.0,4021.0,6014.0,4181.0,1936.0,1488.0,1325.0,1000.0
572,2호선,홍대입구,Friday,승차,483.0,779.0,2257.0,2841.0,1709.0,1165.0,...,1942.0,2349.0,2938.0,4067.0,5489.0,3913.0,3537.0,4654.0,4815.0,1807.0
573,2호선,홍대입구,Friday,하차,120.0,520.0,1204.0,3801.0,3905.0,2346.0,...,3076.0,3157.0,3538.0,4711.0,7317.0,5435.0,2396.0,1746.0,1566.0,1325.0
574,2호선,홍대입구,holiday,승차,529.0,471.0,491.0,649.0,790.0,886.0,...,1981.0,2404.0,3009.0,3463.0,3447.0,3352.0,3813.0,4503.0,3837.0,1272.0
575,2호선,홍대입구,holiday,하차,76.0,291.0,334.0,586.0,1181.0,1702.0,...,4193.0,4113.0,3910.0,3689.0,3223.0,2185.0,1525.0,1301.0,1002.0,854.0

In [3]:
# 노선도 이미지가 구 역명을 사용하고 있으므로 일단 구 역명을 사용하도록 함
# 마친 위에 각 노선별 역들을 추려놨으니 노선도와 대조하면서 dictionary를 만들었다.
station_need_change = {"강변(동서울터미널)": "강변", "교대(법원.검찰청)": "교대", "구의(광진구청)": "구의", "낙성대(강감찬)": "낙성대", 
                       "대림(구로구청)": "대림", "동대문역사문화공원(DDP)": "동대문역사문화공원", "동대문역사문화공원(DDP)(DDP)": "동대문역사문화공원",
                       "삼성(무역센터)": "삼성", "서울대입구(관악구청)": "서울대입구", "왕십리(성동구청)": "왕십리", "용두(동대문구청)": "용두",
                       "잠실(송파구청)": "잠실", "충정로(경기대입구)": "충정로", "경복궁(정부서울청사)": "경복궁", "남부터미널(예술의전당)": "남부터미널",
                       "동작(현충원)": "동작", "미아(서울사이버대학)": "미아", "성신여대입구(돈암)": "성신여대입구", "수유(강북구청)": "수유",
                       "숙대입구(갈월)": "숙대입구", "이촌(국립중앙박물관)": "이촌", "총신대입구(이수)": "이수(총신대입구)", "한성대입구(삼선교)": "한성대입구",
                       "회현(남대문시장)": "회현", "광나루(장신대)": "광나루", "광화문(세종문화회관)": "광화문", "군자(능동)": "군자",
                       "굽은다리(강동구민회관앞)": "굽은다리", "신정(은행정)": "신정", "아차산(어린이대공원후문)": "아차산", "오목교(목동운동장앞)": "오목교",
                       "올림픽공원(한국체대)": "올림픽공원", "천호(풍납토성)": "천호", "고려대(종암)": "고려대", "광흥창(서강)": "굉흥창",
                       "녹사평(용산구청)": "녹사평", "대흥(서강대앞)": "대흥", "봉화산(서울의료원)": "봉화산", "상월곡(한국과학기술연구원)": "상월곡",
                       "새절(신사)": "새절", "안암(고대병원앞)": "안암", "월곡(동덕여대)": "월곡", "월드컵경기장(성산)": "월드컵경기장",
                       "증산(명지대앞)": "증산", "화랑대(서울여대입구)": "화랑대", "상봉(시외버스터미널)": "상봉", "숭실대입구(살피재)": "숭실대입구",
                       "어린이대공원(세종대)": "어린이대공원", "온수(성공회대입구)": "온수", "용마산(용마폭포공원)": "용마산",
                       "남한산성입구(성남법원.검찰청)": "남한산성입구", "몽촌토성(평화의문)": "몽촌토성"
                    }

In [4]:
#2호선 역명 변경
second_df = df.replace({"역명" : station_need_change })
second_df

,호선,역명,요일,구분,06:00 이전,06:00 ~ 07:00,07:00 ~ 08:00,08:00 ~ 09:00,09:00 ~ 10:00,10:00 ~ 11:00,...,14:00 ~ 15:00,15:00 ~ 16:00,16:00 ~ 17:00,17:00 ~ 18:00,18:00 ~ 19:00,19:00 ~ 20:00,20:00 ~ 21:00,21:00 ~ 22:00,22:00 ~ 23:00,23:00 이후
0,2호선,강남,Monday,승차,224.0,591.0,1455.0,2408.0,1806.0,1633.0,...,3520.0,4520.0,4977.0,8257.0,13935.0,8619.0,5978.0,6759.0,5325.0,1305.0
1,2호선,강남,Monday,하차,467.0,2068.0,6424.0,13785.0,13135.0,5408.0,...,3425.0,3251.0,3136.0,3892.0,5753.0,3498.0,1529.0,1171.0,878.0,499.0
2,2호선,강남,Tuesday,승차,259.0,624.0,1510.0,2409.0,1797.0,1636.0,...,3585.0,4592.0,5131.0,8443.0,13780.0,8462.0,6200.0,7238.0,5815.0,1496.0
3,2호선,강남,Tuesday,하차,472.0,2012.0,6365.0,13685.0,13043.0,5436.0,...,3486.0,3308.0,3227.0,4098.0,6205.0,3818.0,1593.0,1247.0,1007.0,572.0
4,2호선,강남,Wednesday,승차,272.0,624.0,1498.0,2392.0,1782.0,1616.0,...,3559.0,4534.0,5051.0,8551.0,13617.0,8221.0,5958.0,7304.0,6089.0,1660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,2호선,홍대입구,Thursday,하차,120.0,515.0,1233.0,3881.0,3962.0,2316.0,...,2785.0,2850.0,3095.0,4021.0,6014.0,4181.0,1936.0,1488.0,1325.0,1000.0
572,2호선,홍대입구,Friday,승차,483.0,779.0,2257.0,2841.0,1709.0,1165.0,...,1942.0,2349.0,2938.0,4067.0,5489.0,3913.0,3537.0,4654.0,4815.0,1807.0
573,2호선,홍대입구,Friday,하차,120.0,520.0,1204.0,3801.0,3905.0,2346.0,...,3076.0,3157.0,3538.0,4711.0,7317.0,5435.0,2396.0,1746.0,1566.0,1325.0
574,2호선,홍대입구,holiday,승차,529.0,471.0,491.0,649.0,790.0,886.0,...,1981.0,2404.0,3009.0,3463.0,3447.0,3352.0,3813.0,4503.0,3837.0,1272.0
575,2호선,홍대입구,holiday,하차,76.0,291.0,334.0,586.0,1181.0,1702.0,...,4193.0,4113.0,3910.0,3689.0,3223.0,2185.0,1525.0,1301.0,1002.0,854.0

In [5]:
#역명 컬럼명 확인
second_df["역명"].unique()

array(['강남', '강변', '건대입구', '교대', '구로디지털단지', '구의', '낙성대', '당산', '대림',
       '도림천', '동대문역사문화공원', '뚝섬', '문래', '방배', '봉천', '사당', '삼성', '상왕십리',
       '서울대입구', '서초', '선릉', '성수', '시청', '신답', '신당', '신대방', '신도림', '신림',
       '신설동', '신정네거리', '신촌', '아현', '양천구청', '역삼', '영등포구청', '왕십리', '용답',
       '용두', '을지로3가', '을지로4가', '을지로입구', '이대', '잠실', '잠실나루', '잠실새내',
       '종합운동장', '충정로', '한양대', '합정', '홍대입구'], dtype=object)

In [28]:
#2호선 최종 parquet 저장
second_df.to_parquet("second-line_per_time.parquet")

In [7]:
#전체 호선 parquet 불러오기
df2 = pd.read_parquet("day-of-week_per_time.parquet")
df2

,호선,역명,요일,구분,06:00 이전,06:00 ~ 07:00,07:00 ~ 08:00,08:00 ~ 09:00,09:00 ~ 10:00,10:00 ~ 11:00,...,14:00 ~ 15:00,15:00 ~ 16:00,16:00 ~ 17:00,17:00 ~ 18:00,18:00 ~ 19:00,19:00 ~ 20:00,20:00 ~ 21:00,21:00 ~ 22:00,22:00 ~ 23:00,23:00 이후
0,1호선,동대문,Monday,승차,485.0,329.0,523.0,682.0,583.0,501.0,...,671.0,700.0,740.0,782.0,814.0,546.0,420.0,396.0,310.0,124.0
1,1호선,동대문,Monday,하차,80.0,247.0,436.0,921.0,813.0,650.0,...,634.0,622.0,565.0,588.0,642.0,723.0,451.0,355.0,325.0,361.0
2,1호선,동대문,Tuesday,승차,499.0,336.0,524.0,696.0,593.0,497.0,...,662.0,702.0,745.0,792.0,822.0,551.0,430.0,413.0,330.0,131.0
3,1호선,동대문,Tuesday,하차,78.0,241.0,437.0,917.0,803.0,647.0,...,626.0,608.0,562.0,592.0,650.0,706.0,449.0,354.0,332.0,370.0
4,1호선,동대문,Wednesday,승차,506.0,331.0,521.0,687.0,590.0,500.0,...,680.0,701.0,750.0,797.0,819.0,539.0,447.0,412.0,323.0,134.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3451,8호선,천호(풍납토성),Thursday,하차,63.0,386.0,581.0,1122.0,837.0,566.0,...,676.0,863.0,1025.0,1440.0,2617.0,1873.0,939.0,851.0,707.0,462.0
3452,8호선,천호(풍납토성),Friday,승차,405.0,639.0,1648.0,2301.0,1211.0,621.0,...,606.0,656.0,752.0,991.0,1194.0,760.0,643.0,504.0,415.0,164.0
3453,8호선,천호(풍납토성),Friday,하차,60.0,376.0,559.0,1095.0,863.0,588.0,...,715.0,934.0,1088.0,1602.0,2846.0,2102.0,1001.0,858.0,743.0,547.0
3454,8호선,천호(풍납토성),holiday,승차,215.0,238.0,327.0,468.0,534.0,472.0,...,577.0,599.0,618.0,628.0,546.0,460.0,471.0,388.0,280.0,105.0
3455,8호선,천호(풍납토성),holiday,하차,40.0,212.0,195.0,264.0,475.0,429.0,...,692.0,749.0,816.0,913.0,839.0,678.0,543.0,570.0,452.0,288.0

In [8]:
#전체 호선 역명 변경
all_df = df2.replace({"역명" : station_need_change })
all_df

,호선,역명,요일,구분,06:00 이전,06:00 ~ 07:00,07:00 ~ 08:00,08:00 ~ 09:00,09:00 ~ 10:00,10:00 ~ 11:00,...,14:00 ~ 15:00,15:00 ~ 16:00,16:00 ~ 17:00,17:00 ~ 18:00,18:00 ~ 19:00,19:00 ~ 20:00,20:00 ~ 21:00,21:00 ~ 22:00,22:00 ~ 23:00,23:00 이후
0,1호선,동대문,Monday,승차,485.0,329.0,523.0,682.0,583.0,501.0,...,671.0,700.0,740.0,782.0,814.0,546.0,420.0,396.0,310.0,124.0
1,1호선,동대문,Monday,하차,80.0,247.0,436.0,921.0,813.0,650.0,...,634.0,622.0,565.0,588.0,642.0,723.0,451.0,355.0,325.0,361.0
2,1호선,동대문,Tuesday,승차,499.0,336.0,524.0,696.0,593.0,497.0,...,662.0,702.0,745.0,792.0,822.0,551.0,430.0,413.0,330.0,131.0
3,1호선,동대문,Tuesday,하차,78.0,241.0,437.0,917.0,803.0,647.0,...,626.0,608.0,562.0,592.0,650.0,706.0,449.0,354.0,332.0,370.0
4,1호선,동대문,Wednesday,승차,506.0,331.0,521.0,687.0,590.0,500.0,...,680.0,701.0,750.0,797.0,819.0,539.0,447.0,412.0,323.0,134.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3451,8호선,천호,Thursday,하차,63.0,386.0,581.0,1122.0,837.0,566.0,...,676.0,863.0,1025.0,1440.0,2617.0,1873.0,939.0,851.0,707.0,462.0
3452,8호선,천호,Friday,승차,405.0,639.0,1648.0,2301.0,1211.0,621.0,...,606.0,656.0,752.0,991.0,1194.0,760.0,643.0,504.0,415.0,164.0
3453,8호선,천호,Friday,하차,60.0,376.0,559.0,1095.0,863.0,588.0,...,715.0,934.0,1088.0,1602.0,2846.0,2102.0,1001.0,858.0,743.0,547.0
3454,8호선,천호,holiday,승차,215.0,238.0,327.0,468.0,534.0,472.0,...,577.0,599.0,618.0,628.0,546.0,460.0,471.0,388.0,280.0,105.0
3455,8호선,천호,holiday,하차,40.0,212.0,195.0,264.0,475.0,429.0,...,692.0,749.0,816.0,913.0,839.0,678.0,543.0,570.0,452.0,288.0

In [31]:
#전체 호선 최종 parquet 저장
all_df.to_parquet("all_line_per_time.parquet")

## 2. 데이터 전처리 과정

* 위 전체노선을 parquet으로 저장하여 주었으나 역명이 통일이 안된것이 있어서 다시 수정작업을 하려고함.
* csv라는 파일을 받았으므로 역명을 기준으로 정렬하여 두개의 데이터프레임의 역명이 같은지 확인!

In [9]:
#전체노선 역명을 정렬 후 확인
all_df = all_df.sort_values("역명")
all_df["역명"].unique()

array(['가락시장', '가산디지털단지', '강남', '강남구청', '강동', '강동구청', '강변', '강일', '개롱',
       '개화산', '거여', '건대입구', '경복궁', '경찰병원', '고덕', '고려대', '고속터미널', '공덕',
       '공릉(서울과학기술대)', '광나루', '광명사거리', '광화문', '굉흥창', '교대', '구로디지털단지', '구산',
       '구의', '구파발', '군자', '굴포천', '굽은다리', '금호', '길동', '길음', '김포공항', '까치산',
       '까치울', '낙성대', '남구로', '남부터미널', '남성', '남태령', '남한산성입구', '내방', '노원',
       '녹번', '녹사평', '논현', '단대오거리', '답십리', '당고개', '당산', '대림', '대청', '대치',
       '대흥', '도곡', '도림천', '도봉산', '독립문', '독바위', '돌곶이', '동대문', '동대문역사문화공원',
       '동대입구', '동묘앞', '동작', '둔촌동', '디지털미디어시티', '뚝섬', '뚝섬유원지', '마곡', '마들',
       '마장', '마천', '마포', '마포구청', '망원', '매봉', '먹골', '면목', '명동', '명일', '모란',
       '목동', '몽촌토성', '무악재', '문래', '문정', '미사', '미아', '미아사거리', '반포', '발산',
       '방배', '방이', '방화', '버티고개', '보라매', '보문', '복정', '봉천', '봉화산', '부천시청',
       '부천종합운동장', '부평구청', '불광', '사가정', '사당', '산성', '삼각지', '삼산체육관', '삼성',
       '상계', '상도', '상동', '상봉', '상수', '상왕십리', '상월곡', '상일동', '새절', '서대문',
       '서울대입구', '서울역', '서초', '석계', '석촌', '선릉', '성수', '성신여대입구', '송정', '송파',
       '수락산', '수서', '수유', '수진', '숙대입구', '숭실대입구', '시청', '신금호', '신길', '신내',
       '신답', '신당', '신대방', '신대방삼거리', '신도림', '신림', '신사', '신설동', '신용산', '신정',
       '신정네거리', '신중동', '신촌', '신풍', '신흥', '쌍문', '아차산', '아현', '안국', '안암',
       '암사', '압구정', '애오개', '약수', '양재(서초구청)', '양천구청', '양평', '어린이대공원',
       '여의나루', '여의도', '역삼', '역촌', '연신내', '영등포구청', '영등포시장', '오금', '오목교',
       '옥수', '온수', '올림픽공원', '왕십리', '용답', '용두', '용마산', '우장산', '월곡',
       '월드컵경기장', '을지로3가', '을지로4가', '을지로입구', '응암', '이대', '이수', '이수(총신대입구)',
       '이촌', '이태원', '일원', '잠실', '잠실나루', '잠실새내', '잠원', '장승배기', '장암', '장지',
       '장한평', '제기동', '종각', '종로3가', '종로5가', '종합운동장', '중계', '중곡', '중화',
       '증산', '지축', '창동', '창신', '천왕', '천호', '철산', '청구', '청담',
       '청량리(서울시립대입구)', '춘의', '충무로', '충정로', '태릉입구', '하계', '하남검단산',
       '하남시청(덕풍·신장)', '하남풍산', '학동', '학여울', '한강진', '한성대입구', '한양대', '합정',
       '행당', '혜화', '홍대입구', '홍제', '화곡', '화랑대', '회현', '효창공원앞'], dtype=object)

In [34]:
#받은 csv파일 불러오기
name = pd.read_csv("csv.csv", encoding='euc-kr')
name

     Unnamed: 0   노선      역명           X           Y
0             0  1호선     청량리  829.755454  615.131004
1             1  1호선     제기동  800.306287  615.956332
2             2  1호선     동묘앞  728.438230  615.666667
3             3  1호선     동대문  668.796274  615.815790
4             4  1호선    종로5가  633.729462  615.815790
..          ...  ...     ...         ...         ...
267         267  8호선  남한산성입구  922.109375  200.528409
268         268  8호선   단대오거리  948.140625  200.528409
269         269  8호선      신흥  973.102273  200.528409
270         270  8호선      수진  973.102273  181.115057
271         271  8호선      모란  973.102273  159.884943

[272 rows x 5 columns]

In [35]:
#정렬 후 확인
name = name.sort_values("역명")
name["역명"].unique()

array(['가락시장', '가산디지털단지', '강남', '강남구청', '강동', '강동구청', '강변', '개롱', '개화산',
       '거여', '건대입구', '경마공원', '경복궁', '경찰병원', '고덕', '고려대', '고속터미널', '고잔',
       '공덕', '공릉', '과천', '광나루', '광명사거리', '광화문', '광흥창', '교대', '구로 디지털단지',
       '구산', '구의', '구파발', '군자', '굴포천', '굽은다리', '금정', '금호', '길동', '길음',
       '김포공항', '까치산', '까치울', '낙성대', '남구로', '남부터미널', '남성', '남태령', '남한산성입구',
       '내방', '노원', '녹번', '녹사평', '논현', '단대오거리', '답십리', '당고개', '당산', '대곡',
       '대공원', '대림', '대야미', '대청', '대치', '대화', '대흥', '도곡', '도림천', '도봉산',
       '독립문', '독바위', '돌곶이', '동대문', '동대문역사문화공원(DDP)', '동대입구', '동묘앞', '동작',
       '둔촌동', '디지털미디어시티', '뚝섬', '뚝섬유원지', '마곡', '마두', '마들', '마장', '마천',
       '마포', '마포구청', '망원', '매봉', '먹골', '면목', '명동', '명일', '모란', '목동',
       '몽촌토성', '무악재', '문래', '문정', '미아', '미아사거리', '반월', '반포', '발산', '방배',
       '방이', '방화', '백석', '버티고개', '범계', '보라매', '보문', '복정', '봉천', '봉화산',
       '부천시청', '부천종합운동장', '부평구청', '불광', '사가정', '사당', '산본', '산성', '삼각지',
       '삼산체육관', '삼성', '삼송', '상계', '상도', '상동', '상록수', '상봉', '상수', '상왕십리',
       '상월곡', '상일동', '서대문', '서울대입구', '서울역', '서초', '석계', '석촌', '선릉', '선바위',
       '성수', '성신여대입구', '세절', '송정', '송파', '수락산', '수리산', '수서', '수유', '수진',
       '숙대입구', '숭실대입구', '시청', '신금호', '신길', '신길온천', '신답', '신당', '신대방',
       '신대방삼거리', '신도림', '신림', '신사', '신설동', '신용산', '신정', '신정네거리', '신중동',
       '신천', '신촌', '신풍', '신흥', '쌍문', '아차산', '아현', '안국', '안산', '안암', '암사',
       '압구정', '애오개', '약수', '양재', '양천구청', '양평', '어린이대공원', '여의나루', '여의도',
       '역삼', '역촌', '연신내', '영등포구청', '영등포시장', '오금', '오목교', '오이도', '옥수',
       '온수', '올림픽공원', '왕십리', '용답', '용두', '용마산', '우장산', '원당', '월곡',
       '월드컵경기장', '을지로3가', '을지로4가', '을지로입구', '응암', '이대', '이수(총신대입구)', '이촌',
       '이태원', '인덕원', '일원', '잠실', '잠실나루', '잠원', '장승배기', '장암', '장지', '장한평',
       '정발산', '정부과천청사', '정왕', '제기동', '종각', '종로3가', '종로5가', '종합운동장', '주엽',
       '중계', '중곡', '중앙', '중화', '증산', '지축', '창동', '창신', '천왕', '천호', '철산',
       '청구', '청담', '청량리', '초지', '춘의', '충무로', '충정로', '태릉입구', '평촌', '하계',
       '학동', '학여울', '한강진', '한대앞', '한성대입구', '한양대', '합정', '행당', '혜화',
       '홍대입구', '홍제', '화곡', '화랑대', '화정', '회현', '효창공원앞'], dtype=object)

### * 비교 결과

* 문제 : 역명이 일치하지 않아 태블로에 역 좌표를 찍을 때 그 데이터가 나타나지 않는 현상이 발생.
* 문제 해결 : 좌표를 기준을 잡아야하므로 좌표에 있는 역들과 가지고 있는 데이터의 역들을 변경하거나 제거하여 일치 시켜줘야함.

1. 데이터에는 있고 좌표에는 없는 역

* 5호선(신설역) : 강일, 미사, 하남검단산, 하남시청(덕풍·신장),하남풍산
* 6호선(신설역) : 신내

2. 데이터에는 없고 좌표에는 있는 역 

* 3호선(일산선) : 대곡, 대화, 마두, 백석, 삼송, 원당, 정발산, 주엽, 화정
* 4호선(과천선) : 경마공원, 과천, 범계, 선바위, 인덕원, 정부과천청사, 평촌
* 4호선(안산선) : 고잔, 금정,  대야미, 산본, 상록수, 수리산, 신길온천, 안산, 오이도, 정왕,  중앙, 초지, 한대앞

3. 이름 바꿔야할 것

* 공릉(서울과학기술대) >> 공릉
    * 구로디지털단지 >> 구로 디지털단지>>> 좌표에서 바꿈!
    * 동대문역사문화공원 >> 동대문역사문화공원(DDP) >>> 좌표에서 바꿈!
    * 새절 >> 세절 >>> 좌표에서 바꿈!
    * 잠실새내 >> 신천 >>> 좌표에서 바꿈!
* 양재(서초구청) >> 양재
* 이수 >>이수(총신대입구)
* 청량리(서울시립대입구) >> 청량리


* 결론 : 1번은 좌표에 없으므로 놔두고, 2번은 좌표를 제거해주고, 나는 3번만 바꿔주면 완료!

In [10]:
#딕셔너리에 변경해주려는 것으로 다시 설정.
station_need_change = {"강변(동서울터미널)": "강변", "교대(법원.검찰청)": "교대", "구의(광진구청)": "구의", "낙성대(강감찬)": "낙성대", 
                       "대림(구로구청)": "대림", "동대문역사문화공원(DDP)(DDP)": "동대문역사문화공원(DDP)",
                       "삼성(무역센터)": "삼성", "서울대입구(관악구청)": "서울대입구", "왕십리(성동구청)": "왕십리", "용두(동대문구청)": "용두",
                       "잠실(송파구청)": "잠실", "충정로(경기대입구)": "충정로", "경복궁(정부서울청사)": "경복궁", "남부터미널(예술의전당)": "남부터미널",
                       "동작(현충원)": "동작", "미아(서울사이버대학)": "미아", "성신여대입구(돈암)": "성신여대입구", "수유(강북구청)": "수유",
                       "숙대입구(갈월)": "숙대입구", "이촌(국립중앙박물관)": "이촌", "총신대입구(이수)": "이수(총신대입구)", "한성대입구(삼선교)": "한성대입구",
                       "회현(남대문시장)": "회현", "광나루(장신대)": "광나루", "광화문(세종문화회관)": "광화문", "군자(능동)": "군자",
                       "굽은다리(강동구민회관앞)": "굽은다리", "신정(은행정)": "신정", "아차산(어린이대공원후문)": "아차산", "오목교(목동운동장앞)": "오목교",
                       "올림픽공원(한국체대)": "올림픽공원", "천호(풍납토성)": "천호", "고려대(종암)": "고려대", "광흥창(서강)": "굉흥창",
                       "녹사평(용산구청)": "녹사평", "대흥(서강대앞)": "대흥", "봉화산(서울의료원)": "봉화산", "상월곡(한국과학기술연구원)": "상월곡",
                       "새절(신사)": "새절", "안암(고대병원앞)": "안암", "월곡(동덕여대)": "월곡", "월드컵경기장(성산)": "월드컵경기장",
                       "증산(명지대앞)": "증산", "화랑대(서울여대입구)": "화랑대", "상봉(시외버스터미널)": "상봉", "숭실대입구(살피재)": "숭실대입구",
                       "어린이대공원(세종대)": "어린이대공원", "온수(성공회대입구)": "온수", "용마산(용마폭포공원)": "용마산",
                       "남한산성입구(성남법원.검찰청)": "남한산성입구", "몽촌토성(평화의문)": "몽촌토성", "공릉(서울과학기술대)" : "공릉",
                       "양재(서초구청)" : "양재", "이수" : "이수(총신대입구)", "청량리(서울시립대입구)" : "청량리"
                    }

In [28]:
#전체 호선 역명 다시 변경
all_df = df2.replace({"역명" : station_need_change })
all_df

,호선,역명,요일,구분,06:00 이전,06:00 ~ 07:00,07:00 ~ 08:00,08:00 ~ 09:00,09:00 ~ 10:00,10:00 ~ 11:00,...,14:00 ~ 15:00,15:00 ~ 16:00,16:00 ~ 17:00,17:00 ~ 18:00,18:00 ~ 19:00,19:00 ~ 20:00,20:00 ~ 21:00,21:00 ~ 22:00,22:00 ~ 23:00,23:00 이후
0,1호선,동대문,Monday,승차,485.0,329.0,523.0,682.0,583.0,501.0,...,671.0,700.0,740.0,782.0,814.0,546.0,420.0,396.0,310.0,124.0
1,1호선,동대문,Monday,하차,80.0,247.0,436.0,921.0,813.0,650.0,...,634.0,622.0,565.0,588.0,642.0,723.0,451.0,355.0,325.0,361.0
2,1호선,동대문,Tuesday,승차,499.0,336.0,524.0,696.0,593.0,497.0,...,662.0,702.0,745.0,792.0,822.0,551.0,430.0,413.0,330.0,131.0
3,1호선,동대문,Tuesday,하차,78.0,241.0,437.0,917.0,803.0,647.0,...,626.0,608.0,562.0,592.0,650.0,706.0,449.0,354.0,332.0,370.0
4,1호선,동대문,Wednesday,승차,506.0,331.0,521.0,687.0,590.0,500.0,...,680.0,701.0,750.0,797.0,819.0,539.0,447.0,412.0,323.0,134.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3451,8호선,천호,Thursday,하차,63.0,386.0,581.0,1122.0,837.0,566.0,...,676.0,863.0,1025.0,1440.0,2617.0,1873.0,939.0,851.0,707.0,462.0
3452,8호선,천호,Friday,승차,405.0,639.0,1648.0,2301.0,1211.0,621.0,...,606.0,656.0,752.0,991.0,1194.0,760.0,643.0,504.0,415.0,164.0
3453,8호선,천호,Friday,하차,60.0,376.0,559.0,1095.0,863.0,588.0,...,715.0,934.0,1088.0,1602.0,2846.0,2102.0,1001.0,858.0,743.0,547.0
3454,8호선,천호,holiday,승차,215.0,238.0,327.0,468.0,534.0,472.0,...,577.0,599.0,618.0,628.0,546.0,460.0,471.0,388.0,280.0,105.0
3455,8호선,천호,holiday,하차,40.0,212.0,195.0,264.0,475.0,429.0,...,692.0,749.0,816.0,913.0,839.0,678.0,543.0,570.0,452.0,288.0

In [29]:
#개수 확인
all_df["역명"].value_count()

동대문역사문화공원(DDP)    72
종로3가              36
청구                24
동묘앞               24
사당                24
                  ..
몽촌토성              12
부평구청              12
중계                12
양재                12
어린이대공원            12
Name: 역명, Length: 247, dtype: int64

### 참고사항

* 위에 보면 동대문역사문화공원은 36개여야한다. 즉 컬럼명 변경만 해주어서 합쳐지지가않음
* 그래서 groupby로 다시 나누려 했으나 나누어지지 않음
* 그래서 맨 처음 부분에서 이름을 변경을해주기로 결정(6번 파일에 위 코드를 이용하여 풀었음)